### ISSUE TITLE
Insufficient logging for RetryRequestExecutor

### ISSUE THREAD

**Issue by JesseJ** [okta/okta-commons-java#31]
I see in our logs that we have 

```txt
2020-01-18 01:43:01,657 [mc-25] WARN  com.okta.sdk.impl.http.RetryRequestExecutor- Unable to pause for retry: Cannot retry request, next request will exceed retry configuration.
2020-01-18 01:43:01,657 [mc-25] ERROR className- An error has occurred while attempting to authenticate the user
com.okta.sdk.impl.http.RestException: Unable to execute HTTP request: Cannot retry request, next request will exceed retry configuration.
	at com.okta.sdk.impl.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:111) ~[okta-sdk-impl-1.5.2.jar:1.5.2]
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:435) ~[okta-sdk-impl-1.5.2.jar:1.5.2]
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$save$1(DefaultDataStore.java:314) ~[okta-sdk-impl-1.5.2.jar:1.5.2]
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47) ~[okta-sdk-impl-1.5.2.jar:1.5.2]
```

However there's no logging as to the reason why it had to retry several times.

**Comment by bdemers** [comment]
Hey @JesseJ!
Sorry about the delay.  Are you still running into this issue?  If you increase the logging level you will get more verbose information about retry attempts.  These retry attempts are normal and expected for a number of reasons (general connectivity errors, rate limiting, stale connection pool, etc).

My suggestion would be to take a look at your [retry config](https://github.com/okta/okta-sdk-java#connection-retry--rate-limiting) and tweak them for your needs. A general recommendation would be to use a short timeout for UI based applications (when you don't want a user to wait longer than X time), and a longer time out, possibly a max retry count for backend or corn tasks that are not timing-dependent.

**Comment by arvindkrishnakumar-okta** [comment]
Just release version `1.2.4` and this addresses the above.
