### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException at com.okta.commons.lang.ApplicationInfo.getWebSphereVersion

### ISSUE THREAD

**Issue by BalusC** [okta/okta-commons-java#70]
Running an Okta API client (e.g. okta-sdk-impl and okta-jwt-verifier-impl) on an environment with WebSphere dependencies declared as runtime dependencies but with WebSphere server itself being physically shutdown (e.g. during local testing) throws the following exception (okta-commons-lang 1.3.0):

```
Caused by: java.lang.StringIndexOutOfBoundsException: begin -1, end 0, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at java.base/java.lang.String.substring(String.java:2677)
	at com.okta.commons.lang.ApplicationInfo.getWebSphereVersion(ApplicationInfo.java:301)
	at com.okta.commons.lang.ApplicationInfo.getWebSphereEntryInfo(ApplicationInfo.java:190)
	at com.okta.commons.lang.ApplicationInfo.getWebServerInfo(ApplicationInfo.java:169)
	at com.okta.commons.lang.ApplicationInfo.createNameToVersionMap(ApplicationInfo.java:105)
	at com.okta.commons.lang.ApplicationInfo.<clinit>(ApplicationInfo.java:90)
	... 8 more
```

I propose to just return `UNKNOWN_VERSION` instead.

**Comment by sergiishamrai-okta** [comment]
Hi @BalusC ,
Thanks for the question.
Can you drop a full stack trace, please?

The `getWebSphereVersion` method will return `UNKNOWN_VERSION` in case of not properly handling some WebSphere version.
[source code is here](https://github.com/okta/okta-commons-java/blob/34b4a322e5d4d9e106ed2f8bb657f849dec84e08/lang/src/main/java/com/okta/commons/lang/ApplicationInfo.java#L312)

**Comment by BalusC** [comment]
`StringIndexOutOfBoundsException` is a subclass of `RuntimeException` so it will be rethrown as can be seen here: https://github.com/okta/okta-commons-java/blob/34b4a322e5d4d9e106ed2f8bb657f849dec84e08/lang/src/main/java/com/okta/commons/lang/ApplicationInfo.java#L306

**Comment by sergiishamrai-okta** [comment]
@BalusC Thank you for your help in improving this library.

**Comment by BalusC** [comment]
For your information, I've just tried 1.3.1-SNAPSHOT from this branch and it works now. Thank you!
